import { UserState, MoodEntry } from '../types';
import { Database } from '../database/db';

export interface ClinicalSummary {
  generatedAt: string;
  campaignWeek: number;
  clinicalPhase: string;
  energyTier: string;
  vitalityPoints: number;
  clarityMana: number;
  gloomClearedPercent: number;
  moodCheckInCount: number;
  averageValence: number | null;
  averageArousal: number | null;
  thoughtsReframed: number;
  questsCompleted: number;
  codexEntries: number;
  streakResonance: string;
}

/**
 * Builds a genuine clinical progress summary from persisted data and opens
 * the OS share sheet. No PDF generation — a clean text summary is more
 * portable (email, messaging, patient portal) and needs no native module.
 */
export class ClinicalExportService {
  async buildSummary(userState: UserState): Promise<ClinicalSummary> {
    const [moodLogs, codex] = await Promise.all([
      Database.getMoodLogs(),
      Database.getVictoryCodex(),
    ]);

    const valences = moodLogs.map((m) => m.valence);
    const arousals = moodLogs.map((m) => m.arousal);

    const quests = await Database.getQuests();

    return {
      generatedAt: new Date().toISOString(),
      campaignWeek: userState.campaignWeek,
      clinicalPhase: userState.clinicalPhase,
      energyTier: userState.energyTier,
      vitalityPoints: userState.vitalityPoints,
      clarityMana: userState.clarityMana,
      gloomClearedPercent: Number(userState.sanctuary.gloomClearingPercentage.toFixed(1)),
      moodCheckInCount: moodLogs.length,
      averageValence: valences.length
        ? Number((valences.reduce((a, b) => a + b, 0) / valences.length).toFixed(2))
        : null,
      averageArousal: arousals.length
        ? Number((arousals.reduce((a, b) => a + b, 0) / arousals.length).toFixed(2))
        : null,
      thoughtsReframed: codex.length,
      questsCompleted: quests.filter((q) => q.isCompleted).length,
      codexEntries: codex.length,
      streakResonance: `${Math.round(userState.vitalityResonance * 100)}%`,
    };
  }

  formatAsText(s: ClinicalSummary): string {
    const fmt = (v: number | null, suffix = '') => (v === null ? '—' : `${v}${suffix}`);
    return [
      'AETHERIA — CLINICAL PROGRESS SUMMARY',
      `Generated: ${new Date(s.generatedAt).toLocaleString()}`,
      '',
      'PROGRAM',
      `• Week ${s.campaignWeek} of 8 (${s.clinicalPhase})`,
      `• Energy self-report tier: ${s.energyTier}`,
      `• Vitality Resonance (adherence proxy): ${s.streakResonance}`,
      '',
      'ENGAGEMENT',
      `• Quests completed: ${s.questsCompleted}`,
      `• Thoughts reframed (Socratic exercises): ${s.thoughtsReframed}`,
      `• Codex entries saved: ${s.codexEntries}`,
      '',
      'MOOD CHECK-INS',
      `• Total check-ins: ${s.moodCheckInCount}`,
      `• Average valence: ${fmt(s.averageValence)} (-5..+5 scale)`,
      `• Average arousal: ${fmt(s.averageArousal)} (-5..+5 scale)`,
      '',
      'Generated by Aetheria: The Cognitive Quest (self-help tool, not medical advice).',
      'This summary is intended to support a conversation with a healthcare professional.',
    ].join('\n');
  }

  async exportAndShare(userState: UserState): Promise<boolean> {
    try {
      const { Share } = require('react-native');
      const summary = await this.buildSummary(userState);
      await Share.share({
        title: 'Aetheria Clinical Progress Summary',
        message: this.formatAsText(summary),
      });
      return true;
    } catch (e) {
      console.warn('[ClinicalExport] Share failed', e);
      return false;
    }
  }
}

export const ClinicalExport = new ClinicalExportService();
