import { StyleSheet } from 'react-native';
import { Colors, Spacing } from '../../../core/theme';

/** Shared styles for AcademyScreen and its child components */
export const academyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: Spacing.md,
    paddingBottom: Spacing.xxl,
  },
  headerCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: Spacing.md,
  },
  headerTitle: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  headerSubtitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  syncBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderWidth: 1,
    borderColor: Colors.clarityMana,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    gap: 4,
  },
  syncBtnDisabled: {
    opacity: 0.6,
  },
  syncBtnText: {
    color: Colors.clarityMana,
    fontSize: 10,
    fontWeight: '700',
  },
  recallDueCard: {
    backgroundColor: 'rgba(251, 191, 36, 0.08)',
    borderRadius: 14,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.reframeGold,
    marginBottom: Spacing.md,
  },
  recallDueTitle: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  recallDueBadge: {
    backgroundColor: Colors.reframeGold,
    color: '#0A0A0E',
    fontSize: 9,
    fontWeight: '800',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  recallDueSubtext: {
    color: Colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  recallItemBtn: {
    backgroundColor: Colors.surface,
    padding: Spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
    minWidth: 140,
  },
  recallItemTitle: {
    color: Colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  recallItemStars: {
    color: Colors.reframeGold,
    fontSize: 10,
    fontWeight: '600',
  },
  categoriesRow: {
    gap: 6,
    paddingVertical: Spacing.xs,
    marginBottom: Spacing.md,
  },
  categoryChip: {
    backgroundColor: Colors.surface,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  categoryChipActive: {
    backgroundColor: 'rgba(251, 191, 36, 0.15)',
    borderColor: Colors.reframeGold,
  },
  categoryChipText: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  categoryChipTextActive: {
    color: Colors.reframeGold,
    fontWeight: '700',
  },
  scrollsGrid: {
    gap: Spacing.md,
  },
  scrollCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  scrollCardCompleted: {
    borderColor: 'rgba(16, 185, 129, 0.4)',
    backgroundColor: 'rgba(16, 185, 129, 0.03)',
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.xs,
  },
  iconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(251, 191, 36, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainerCompleted: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
  },
  l2Badge: {
    backgroundColor: 'rgba(56, 189, 248, 0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Colors.shieldCyan,
  },
  l2BadgeText: {
    color: Colors.shieldCyan,
    fontSize: 9,
    fontWeight: '700',
  },
  completedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  completedText: {
    color: Colors.vitalityGreen,
    fontSize: 10,
    fontWeight: '700',
  },
  scrollTitle: {
    color: Colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 4,
  },
  scrollSubtitle: {
    color: Colors.reframeGold,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  scrollAuthor: {
    color: Colors.textMuted,
    fontSize: 11,
    marginTop: 4,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.sm,
    paddingTop: Spacing.xs,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  cardRewardText: {
    color: Colors.clarityMana,
    fontSize: 11,
    fontWeight: '600',
  },
  routineCountText: {
    color: Colors.textMuted,
    fontSize: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  modalCategory: {
    color: Colors.reframeGold,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  modalTitle: {
    color: Colors.textPrimary,
    fontSize: 17,
    fontWeight: '700',
    marginTop: 2,
  },
  modalAuthor: {
    color: Colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  closeBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: Colors.surfaceLight,
  },
  modalTabsRow: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingHorizontal: Spacing.xs,
  },
  modalTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 4,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  modalTabBtnActive: {
    borderBottomColor: Colors.reframeGold,
  },
  modalTabText: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  modalTabTextActive: {
    color: Colors.reframeGold,
    fontWeight: '700',
  },
  modalBody: {
    padding: Spacing.md,
  },
  scrollBodyText: {
    color: Colors.textPrimary,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: Spacing.md,
  },
  takeawayBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(251, 191, 36, 0.08)',
    borderWidth: 1,
    borderColor: Colors.reframeGold,
    borderRadius: 10,
    padding: Spacing.md,
    gap: 10,
    marginBottom: Spacing.md,
  },
  takeawayLabel: {
    color: Colors.reframeGold,
    fontSize: 12,
    fontWeight: '700',
  },
  takeawayText: {
    color: Colors.textPrimary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  l2HeaderBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: 'rgba(56, 189, 248, 0.08)',
    borderWidth: 1,
    borderColor: Colors.shieldCyan,
    borderRadius: 10,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  l2Title: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  l2Subtitle: {
    color: Colors.shieldCyan,
    fontSize: 11,
    marginTop: 2,
  },
  caseStudyBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderLeftWidth: 3,
    borderLeftColor: Colors.distortionRed,
    padding: Spacing.sm,
    borderRadius: 6,
    marginBottom: Spacing.md,
  },
  caseStudyLabel: {
    color: Colors.distortionRed,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  caseStudyText: {
    color: Colors.textPrimary,
    fontSize: 12,
    lineHeight: 17,
  },
  routinesIntroText: {
    color: Colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  routineCard: {
    backgroundColor: Colors.surface,
    padding: Spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  routineTitle: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  routineDesc: {
    color: Colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  routineRationale: {
    color: Colors.reframeGold,
    fontSize: 10,
    marginTop: 4,
  },
  timeTag: {
    backgroundColor: 'rgba(251, 191, 36, 0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Colors.reframeGold,
  },
  timeTagText: {
    color: Colors.reframeGold,
    fontSize: 10,
    fontWeight: '700',
  },
  addRoutineBtn: {
    backgroundColor: Colors.vitalityGreen,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
    marginTop: Spacing.sm,
  },
  addRoutineBtnText: {
    color: '#0A0A0E',
    fontSize: 11,
    fontWeight: '700',
  },
  memoryStrengthBox: {
    backgroundColor: Colors.surface,
    padding: Spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  memoryStrengthTitle: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  memoryStrengthSubtext: {
    color: Colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  recallCard: {
    backgroundColor: Colors.surface,
    padding: Spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  recallPrompt: {
    color: Colors.clarityMana,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
  },
  recallQuestion: {
    color: Colors.textPrimary,
    fontSize: 12,
    lineHeight: 16,
  },
  recallInsight: {
    color: Colors.reframeGold,
    fontSize: 10,
    marginTop: 6,
  },
  quizContainer: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: Spacing.sm,
  },
  quizHeader: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: Spacing.xs,
  },
  questionBlock: {
    marginBottom: Spacing.md,
  },
  questionText: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  quizOption: {
    backgroundColor: Colors.surfaceLight,
    padding: Spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  quizOptionSelected: {
    borderColor: Colors.clarityMana,
    backgroundColor: 'rgba(56, 189, 248, 0.1)',
  },
  quizOptionCorrect: {
    borderColor: Colors.vitalityGreen,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  quizOptionWrong: {
    borderColor: Colors.distortionRed,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  quizOptionText: {
    color: Colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  explanationText: {
    color: Colors.reframeGold,
    fontSize: 11,
    marginTop: 6,
    lineHeight: 15,
  },
  resultBanner: {
    padding: Spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: Spacing.md,
  },
  resultBannerSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: Colors.vitalityGreen,
  },
  resultBannerFail: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: Colors.distortionRed,
  },
  resultBannerTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  resultBannerDesc: {
    color: Colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  submitQuizBtn: {
    backgroundColor: Colors.reframeGold,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
    marginTop: Spacing.xs,
  },
  submitQuizBtnText: {
    color: '#0A0A0E',
    fontSize: 13,
    fontWeight: '700',
  },
  retryBtn: {
    backgroundColor: Colors.surfaceLight,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  retryBtnText: {
    color: Colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  recallModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.md,
  },
  recallModalBox: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.reframeGold,
  },
  recallModalHeading: {
    color: Colors.reframeGold,
    fontSize: 14,
    fontWeight: '700',
  },
  recallBookTitle: {
    color: Colors.textMuted,
    fontSize: 11,
    marginBottom: 4,
  },
  recallModalPrompt: {
    color: Colors.clarityMana,
    fontSize: 11,
    fontWeight: '700',
  },
  recallModalQuestion: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
    lineHeight: 18,
  },
});
