// Auto-extracted seed content from core/database/db.ts (Phase 3 refactor)
import { ThoughtFeedItem } from '../core/types';

export const INITIAL_THOUGHT_FEED: ThoughtFeedItem[] = [
        {
          id: 'thg_parent_1',
          thought: 'My 4-year-old is having a screaming bedtime meltdown. I must be failing as a father because good parents have calm children.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Equating a child’s normal developmental emotional dysregulation with complete parental failure.',
          techniqueOptions: ['SOMATIC_COREGULATION', 'CFT_COMPASSION', 'CBT_REALITY_CHECK'],
          suggestedReframe: 'Toddler tantrums are neurological overwhelm, not a referendum on my parenting. My job is to be the calm anchor.',
          reframeOptions: [
            {
              id: 'ref_p1_opt',
              text: 'Toddler meltdowns are a normal part of nervous system development, not proof of bad parenting. My role is to stay calm and co-regulate.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Applies Somatic Co-Regulation and CBT evidence testing; removes shame.',
              clinicalFeedback: 'Masterful reframe. Decouples your worth from toddler dysregulation.',
            },
            {
              id: 'ref_p1_toxic',
              text: 'Everything is fine! Children are a blessing and I should feel lucky and smile through every scream!',
              type: 'TOXIC_POSITIVITY',
              score: 45,
              explanation: 'Invalidates genuine exhaustion with superficial positivity.',
              clinicalFeedback: 'Toxic positivity suppresses real emotional strain and leads to sudden snapping.',
            },
            {
              id: 'ref_p1_rat',
              text: 'Other kids never scream like this. My child is just defiant and I am doomed to have a chaotic home.',
              type: 'RATIONALIZATION',
              score: 25,
              explanation: 'Maintains all-or-nothing thinking and learned helplessness.',
              clinicalFeedback: 'Reinforces helplessness and creates adversarial tension with your child.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_parent_2',
          thought: 'I snapped and raised my voice at the kids during the morning rush. I have permanently damaged our bond and their trust in me.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Blowing a moment of morning frustration into irreversible psychological trauma.',
          techniqueOptions: ['CFT_COMPASSION', 'CBT_REALITY_CHECK', 'SCHEMA_HEALTHY_ADULT'],
          suggestedReframe: 'Losing my temper is human under stress. What builds secure attachment is humble, swift repair and apology.',
          reframeOptions: [
            {
              id: 'ref_p2_opt',
              text: 'Raising my voice was a mistake born of stress, but attachment research proves swift, humble repair and apology actually strengthens trust.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Emphasizes repair over perfection, backed by developmental science.',
              clinicalFeedback: 'Excellent. Demonstrates that authentic repair models emotional maturity for your children.',
            },
            {
              id: 'ref_p2_toxic',
              text: 'They won’t even remember it when they grow up, so there is no point in apologizing or dwelling on it.',
              type: 'TOXIC_POSITIVITY',
              score: 40,
              explanation: 'Dismisses accountability to avoid temporary discomfort.',
              clinicalFeedback: 'Bypassing repair prevents children from learning how healthy adults take ownership.',
            },
            {
              id: 'ref_p2_rat',
              text: 'If they just put their shoes on the first time I asked, I wouldn’t have had to yell. It’s entirely their fault.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Projects adult emotional dysregulation onto young children.',
              clinicalFeedback: 'Blaming children for adult reactivity keeps you stuck in reactive parenting loops.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_parent_3',
          thought: 'I worked late and missed family dinner. A good father should never prioritize work over family time.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'SHOULD_STATEMENTS',
          explanation: 'Applying an impossible, rigid moral standard that ignores realistic professional constraints.',
          techniqueOptions: ['REBT_DISPUTE', 'CFT_COMPASSION', 'ACT_DEFUSION'],
          suggestedReframe: 'I prefer to be at every dinner, but providing for my family requires flexibility. I can be fully present at bedtime.',
          reframeOptions: [
            {
              id: 'ref_p3_opt',
              text: 'I prefer to make every dinner, but working late to provide is also an act of care. I will make our bedtime reading 100% focused.',
              type: 'OPTIMAL',
              score: 95,
              explanation: 'Converts a rigid "should" into a healthy preference and pivots to quality connection.',
              clinicalFeedback: 'Balances realistic career duty with warm, intentional presence.',
            },
            {
              id: 'ref_p3_toxic',
              text: 'Work is all that matters because money buys happiness for the family anyway!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Overcompensates with materialism to avoid emotional guilt.',
              clinicalFeedback: 'Avoids addressing the core desire for meaningful family connection.',
            },
            {
              id: 'ref_p3_rat',
              text: 'I might as well give up on being present during the week since my career completely owns my life.',
              type: 'RATIONALIZATION',
              score: 25,
              explanation: 'All-or-nothing defeatism that abandons micro-moments of evening connection.',
              clinicalFeedback: 'Treats binary trade-offs as absolute, ignoring micro-moments of genuine bonding.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_teach_1',
          thought: 'Half the students were restless and talking during my lesson today. I am a terrible teacher and have lost all classroom control.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Interpreting a single restless period as total pedagogical incompetence.',
          techniqueOptions: ['STOIC_CONTROL', 'CBT_REALITY_CHECK', 'SOMATIC_COREGULATION'],
          suggestedReframe: 'Student energy fluctuates due to time of day and attention spans. One noisy period is feedback for pacing, not a verdict on my skill.',
          reframeOptions: [
            {
              id: 'ref_t1_opt',
              text: 'Classroom energy fluctuates with weather, time of day, and fatigue. One restless session is diagnostic feedback to adjust pacing, not a referendum on my competence.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Separates pedagogical data from personal identity and applies Stoic control.',
              clinicalFeedback: 'Pivots from shame to reflective practitioner mindset.',
            },
            {
              id: 'ref_t1_toxic',
              text: 'It was the best lesson ever, the kids were just expressing their vibrant creative spirits!',
              type: 'TOXIC_POSITIVITY',
              score: 40,
              explanation: 'Ignores actual classroom management needs with romanticized delusion.',
              clinicalFeedback: 'Prevents effective boundary setting and classroom management adjustments.',
            },
            {
              id: 'ref_t1_rat',
              text: 'This generation of students is completely unteachable and there is no point in trying creative lessons.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Bitter cynicism that relieves the educator from trying.',
              clinicalFeedback: 'Cynical surrender that leads directly to educator burnout.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_teach_2',
          thought: 'It is Sunday 8 PM and I still have 35 essays left to grade. If I don’t finish them all tonight with detailed comments, I am failing my students.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'SHOULD_STATEMENTS',
          explanation: 'Sacrificing essential sleep and health to meet an unsustainable standard of perfectionism.',
          techniqueOptions: ['REBT_DISPUTE', 'BA_MICRO_ACTION', 'CFT_COMPASSION'],
          suggestedReframe: 'A rested, emotionally patient teacher in the morning benefits students far more than exhaustive midnight grading.',
          reframeOptions: [
            {
              id: 'ref_t2_opt',
              text: 'A rested, emotionally grounded teacher in the morning is more impactful than midnight feedback. I will grade 10 essays focused on key criteria, then sleep.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Balances teacher sustainability with student utility.',
              clinicalFeedback: 'Protects circadian health and models healthy boundaries.',
            },
            {
              id: 'ref_t2_toxic',
              text: 'I will just stay up until 3 AM with 4 energy drinks! Sleep is for the weak when students depend on me!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Hero/martyr syndrome that guarantees severe burnout.',
              clinicalFeedback: 'Martyrdom leads directly to Monday irritability and morning classroom snap.',
            },
            {
              id: 'ref_t2_rat',
              text: 'Students don’t even read feedback anyway, so I should just give everyone an A and stop grading.',
              type: 'RATIONALIZATION',
              score: 25,
              explanation: 'Defensive dismissiveness that erodes professional pride.',
              clinicalFeedback: 'Devalues your own craft rather than managing workload strategically.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_teach_3',
          thought: 'A parent sent an email saying "We need to talk about my son’s grade." They definitely think I am incompetent and are trying to get me reprimanded.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'MIND_READING',
          explanation: 'Projecting acute catastrophic intentions onto a neutral, standard communication.',
          techniqueOptions: ['CBT_REALITY_CHECK', 'STOIC_CONTROL', 'ACT_DEFUSION'],
          suggestedReframe: 'Parents inquire because they are anxious about their child. I have clear rubrics and can have a collaborative, professional conversation.',
          reframeOptions: [
            {
              id: 'ref_t3_opt',
              text: 'Parents reach out out of anxiety for their child. I have clear rubrics and objective data. I will approach the call as a collaborative team meeting.',
              type: 'OPTIMAL',
              score: 95,
              explanation: 'Tests the mind-reading assumption and approaches the meeting with professional equanimity.',
              clinicalFeedback: 'Defuses threat-defense alarm and establishes collaborative educator boundaries.',
            },
            {
              id: 'ref_t3_toxic',
              text: 'Every parent interaction is a wonderful joy! I will just agree to change the grade immediately to make everyone smile!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'People-pleasing that compromises educational integrity.',
              clinicalFeedback: 'Sacrifices professional standards to avoid mild conflict.',
            },
            {
              id: 'ref_t3_rat',
              text: 'Entitled parents always ruin education. I will write a harsh defensive email right now before they attack me.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Pre-emptive attack driven by defensive fear.',
              clinicalFeedback: 'Escalates conflict unnecessarily before establishing basic facts.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rel_1',
          thought: 'My partner came home exhausted and barely looked up when I spoke. They must be growing distant and falling out of love with me.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'MIND_READING',
          explanation: 'Interpreting another adult’s workplace exhaustion as personal emotional rejection.',
          techniqueOptions: ['CBT_REALITY_CHECK', 'CFT_COMPASSION', 'SCHEMA_HEALTHY_ADULT'],
          suggestedReframe: 'Their quietness is depletion from a grueling day, not a lack of love. I can offer a glass of water and space rather than taking it personally.',
          reframeOptions: [
            {
              id: 'ref_r1_opt',
              text: 'Their flat affect is physiological fatigue from a long day, not an indictment of our relationship. I will offer warmth and give them 20 minutes to decompress.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Separates fatigue from relational bond and offers low-pressure connection.',
              clinicalFeedback: 'Deeply empathic. Breaks the cycle of demand-withdrawal in relationships.',
            },
            {
              id: 'ref_r1_toxic',
              text: 'True soulmates never feel tired around each other! Everything is perfect in our paradise!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Unrealistic fairy-tale standard that breeds dissatisfaction.',
              clinicalFeedback: 'Denies normal human biology and creates artificial pressure.',
            },
            {
              id: 'ref_r1_rat',
              text: 'If they can’t even say hello, I will give them the silent treatment for the rest of the evening.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Punitive retaliation that accelerates marital estrangement.',
              clinicalFeedback: 'Weaponizes passive-aggressive silence, escalating distance.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rel_2',
          thought: 'I did the dishes, packed school lunches, and put the kids to bed while my partner sat on the couch. I do EVERYTHING in this house.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Using absolute terms ("everything / nothing") that erase the partner’s invisible or daily contributions.',
          techniqueOptions: ['CBT_REALITY_CHECK', 'REBT_DISPUTE', 'CFT_COMPASSION'],
          suggestedReframe: 'I carried a heavy load tonight and feel tired. That doesn’t mean they do nothing. I can make a clear, gentle request for help tomorrow.',
          reframeOptions: [
            {
              id: 'ref_r2_opt',
              text: 'I carried a heavy load tonight and feel depleted. Instead of stewing in silent resentment ("I do everything"), I will clearly and kindly ask for specific help tomorrow.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Validates real fatigue while dropping binary blame in favor of assertive communication.',
              clinicalFeedback: 'Replaces passive resentment with constructive, collaborative partnership.',
            },
            {
              id: 'ref_r2_toxic',
              text: 'I love doing all the chores by myself! It’s my secret superpower and I will never complain!',
              type: 'TOXIC_POSITIVITY',
              score: 40,
              explanation: 'Martyr posture that inevitably leads to an explosive blowout.',
              clinicalFeedback: 'Masks burnout with false cheer until emotional exhaustion hits.',
            },
            {
              id: 'ref_r2_rat',
              text: 'My partner is completely useless and I have to accept being a single parent in a marriage.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Contemptuous schema that permanently poisons marital goodwill.',
              clinicalFeedback: 'Contempt is the #1 predictor of relational decay; traps you in victimhood.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rest_1',
          thought: 'I took a 45-minute nap on Sunday afternoon while there was laundry to fold. I am so lazy and wasting precious life.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Equating essential biological restoration with moral defectiveness or laziness.',
          techniqueOptions: ['CFT_COMPASSION', 'CBT_REALITY_CHECK', 'ACT_DEFUSION'],
          suggestedReframe: 'Rest is not a reward you earn only after total exhaustion; it is biological maintenance required to be a patient father and teacher.',
          reframeOptions: [
            {
              id: 'ref_s1_opt',
              text: 'Rest is not laziness; it is biological maintenance. Resting 45 minutes restores my prefrontal patience so I can show up with warmth for my family.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Reframes rest as essential fuel for parental and pedagogical presence.',
              clinicalFeedback: 'Flawless reframe. Dissolves capitalist hustle guilt with biological reality.',
            },
            {
              id: 'ref_s1_toxic',
              text: 'I must never stop moving! High achievers only sleep 4 hours a night and hustle 24/7!',
              type: 'TOXIC_POSITIVITY',
              score: 25,
              explanation: 'Toxic hustle mythology that leads directly to adrenal collapse.',
              clinicalFeedback: 'Glorifies sleep deprivation, accelerating cognitive and somatic breakdown.',
            },
            {
              id: 'ref_s1_rat',
              text: 'Since I took a nap, the whole afternoon is ruined so I might as well scroll on my phone until midnight.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'All-or-nothing spiraling into revenge bedtime procrastination.',
              clinicalFeedback: 'Uses minor deviation as an excuse for reckless avoidance.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rel_3',
          thought: 'We haven’t had a quiet date night in 3 weeks because of child sleep battles and grading. We have turned into boring roommates and our romantic spark is dying.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Interpreting a busy parenting season as the permanent death of romantic love.',
          techniqueOptions: ['CFT_COMPASSION', 'BA_MICRO_ACTION', 'ACT_DEFUSION'],
          suggestedReframe: 'Seasons of intensive parenting naturally compress romantic time. A 10-minute cup of tea together after bedtime preserves our closeness.',
          reframeOptions: [
            {
              id: 'ref_r3_opt',
              text: 'Intensive parenting seasons are naturally crowded. We do not need elaborate 4-hour dates to stay close; a 10-minute quiet evening tea together on the couch keeps our romantic pilot light burning.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Emphasizes micro-moments of connection during busy family seasons.',
              clinicalFeedback: 'Protects marital optimism without requiring unrealistic free time.',
            },
            {
              id: 'ref_r3_toxic',
              text: 'Who needs romance when you have children? Love is totally unnecessary after marriage!',
              type: 'TOXIC_POSITIVITY',
              score: 25,
              explanation: 'Resignation disguised as contentment.',
              clinicalFeedback: 'Suppresses genuine romantic needs.',
            },
            {
              id: 'ref_r3_rat',
              text: 'Since we can’t go on expensive weekends away, there is no point in even talking to each other at night.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'All-or-nothing despair that neglects daily connection.',
              clinicalFeedback: 'Accelerates marital emotional drift.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rest_2',
          thought: 'It is 2:00 AM and I have been awake for 45 minutes. If I don’t fall asleep immediately, my entire teaching and parenting tomorrow is ruined and I will fail.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Catastrophic clock-watching panic that triggers adrenaline and keeps the brain awake.',
          techniqueOptions: ['ACT_DEFUSION', 'SOMATIC_COREGULATION', 'STOIC_CONTROL'],
          suggestedReframe: 'My body is still resting and rejuvenating lying in bed. One fragmented night does not ruin tomorrow; I have functioned well while tired before.',
          reframeOptions: [
            {
              id: 'ref_s2_opt',
              text: 'Tossing and turning panic fuels adrenaline. Lying peacefully in the dark is still biological resting. I have taught and parented successfully while tired before; my body will sleep when ready.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'De-escalates sleep performance anxiety with CBT-I stimulus control and defusion.',
              clinicalFeedback: 'Gold-standard insomnia reframe. Breaks nocturnal panic spirals.',
            },
            {
              id: 'ref_s2_toxic',
              text: 'Sleep is for the weak! I should jump out of bed and clean the entire garage at 2 AM!',
              type: 'TOXIC_POSITIVITY',
              score: 20,
              explanation: 'Hyperactive manic response that ruins circadian rhythms.',
              clinicalFeedback: 'Drives physical exhaustion.',
            },
            {
              id: 'ref_s2_rat',
              text: 'My sleep is permanently broken. I should take 4 sleeping pills and doomscroll until 6 AM.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Despair reaction that creates dependency on unhealthy sleep habits.',
              clinicalFeedback: 'Destroys sleep hygiene and exacerbates insomnia.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rest_3',
          thought: 'I planned to exercise for 30 minutes, but was too physically exhausted after grading. I have zero self-discipline and my physical health is going down the drain.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Equating biological fatigue with moral weakness or lack of discipline.',
          techniqueOptions: ['CFT_COMPASSION', 'BA_MICRO_ACTION', 'STOIC_CONTROL'],
          suggestedReframe: 'Listening to severe fatigue is intelligent body awareness. I will do 3 minutes of gentle stretching on the floor tonight instead.',
          reframeOptions: [
            {
              id: 'ref_s3_opt',
              text: 'Recognizing genuine somatic exhaustion is wise biological stewardship, not weakness. I will honor my body with 3 minutes of gentle floor stretching and an early bedtime tonight.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Replaces all-or-nothing fitness perfectionism with sustainable somatic pacing.',
              clinicalFeedback: 'Prevents the shame-exhaustion spiral in physical health.',
            },
            {
              id: 'ref_s3_toxic',
              text: 'No excuses ever! Push through the pain and do 100 burpees even if fainting!',
              type: 'TOXIC_POSITIVITY',
              score: 25,
              explanation: 'Dangerous toxic hustle culture that causes injuries and adrenal burnout.',
              clinicalFeedback: 'Ignores physical somatic signals.',
            },
            {
              id: 'ref_s3_rat',
              text: 'Since I missed one workout, my body is a lost cause and I might as well eat junk food on the couch.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Classic all-or-nothing dietary abandonment.',
              clinicalFeedback: 'Compounds self-criticism with harmful behaviors.',
            },
          ],
          isSolved: false,
        },
        // --- FATHERHOOD & PARENTING (Continued) ---
        {
          id: 'thg_parent_4',
          thought: 'My 3-year-old refused all vegetables and threw their plate. If I don’t force them to eat now, they will have horrible nutritional habits and poor health for life.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Extrapolating a toddler’s normal developmental sensory picky phase into permanent lifelong physical ruin.',
          techniqueOptions: ['STOIC_CONTROL', 'CBT_REALITY_CHECK', 'SOMATIC_COREGULATION'],
          suggestedReframe: 'Toddlers explore autonomy through food. My job is offering nutritious options; their job is deciding how much to eat. One meal does not determine their lifetime health.',
          reframeOptions: [
            {
              id: 'ref_p4_opt',
              text: 'Toddler picky eating is an autonomy developmental milestone. My duty is offering nutritious food calmly; forcing them creates mealtime anxiety. Long-term health is built over years, not one dinner.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Applies Division of Responsibility in feeding and Stoic control.',
              clinicalFeedback: 'Masterful perspective. Dissolves mealtime power struggles.',
            },
            {
              id: 'ref_p4_toxic',
              text: 'Vegetables are overrated anyway, nuggets and candy are full of pure childhood joy!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Avoids responsible parenting guidance with dismissive cheer.',
              clinicalFeedback: 'Avoids healthy boundary setting.',
            },
            {
              id: 'ref_p4_rat',
              text: 'My child is manipulative and testing me. I must wage a war of attrition at the table to prove who is boss.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Adversarial power struggle that creates feeding aversions.',
              clinicalFeedback: 'Escalates table battles and increases child autonomic defiance.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_parent_5',
          thought: 'My kids are screaming and wrestling on the living room floor. I cannot take this noise for another second; my household is totally out of control.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Interpreting normal high physical sibling energy as a complete breakdown of domestic order.',
          techniqueOptions: ['SOMATIC_COREGULATION', 'BA_MICRO_ACTION', 'STOIC_CONTROL'],
          suggestedReframe: 'High physical play is natural energy discharge. I will take 2 physiological sighs and redirect them outdoors or to an obstacle course.',
          reframeOptions: [
            {
              id: 'ref_p5_opt',
              text: 'Rough-and-tumble play is natural mammalian development, not domestic collapse. I will breathe deeply, step in with calm energy, and channel their physical drive outside.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Applies Somatic Co-Regulation and proactive behavioral redirection.',
              clinicalFeedback: 'Reframes chaotic noise as kinetic energy that just needs an outlet.',
            },
            {
              id: 'ref_p5_toxic',
              text: 'Screaming is the song of angels! I will just sit here smiling while lamps get knocked over!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Passive neglect disguised as patience.',
              clinicalFeedback: 'Fails to provide safe physical containment.',
            },
            {
              id: 'ref_p5_rat',
              text: 'I should ban all playing in the living room forever since they can never behave like civilized adults.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Punitive overreaction expecting adult restraint from young children.',
              clinicalFeedback: 'Imposes unrealistic developmental expectations.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_parent_6',
          thought: 'I saw other dads at the park running effortlessly with their kids while I was sitting exhausted on the bench. I am an inferior, lazy father.',
          contextDomain: 'FATHERHOOD_PARENTING',
          correctDistortion: 'PERSONALIZATION',
          explanation: 'Comparing your internal fatigue to other parents’ external snapshot highlights.',
          techniqueOptions: ['CFT_COMPASSION', 'CBT_REALITY_CHECK', 'ACT_DEFUSION'],
          suggestedReframe: 'I am seeing a 5-minute highlight reel of other families. Being present at the park while honoring my body’s fatigue is dedicated fatherhood.',
          reframeOptions: [
            {
              id: 'ref_p6_opt',
              text: 'Comparing my internal exhaustion to someone else’s 2-minute snapshot is unfair. Bringing my kids to the park and holding space while tired is an act of deep parental love.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Disarms social comparison with compassionate reality testing.',
              clinicalFeedback: 'Validates that showing up while tired is genuine heroism.',
            },
            {
              id: 'ref_p6_toxic',
              text: 'I am the greatest dad on Earth and have zero flaws whatsoever!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Inflated grandiosity that hides underlying insecurity.',
              clinicalFeedback: 'Bypasses the real need for self-acceptance.',
            },
            {
              id: 'ref_p6_rat',
              text: 'I am just genetically unsuited for parenting and should let my partner handle all outings.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Ego evasion to escape physical effort.',
              clinicalFeedback: 'Withdraws from family bonding rather than pacing energy.',
            },
          ],
          isSolved: false,
        },

        // --- TEACHING & EDUCATOR (Continued) ---
        {
          id: 'thg_teach_4',
          thought: 'The principal walked in for an unannounced observation during our rowdiest group activity. My annual evaluation is completely ruined.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Assuming an administrator interprets collaborative student noise as pedagogical incompetence.',
          techniqueOptions: ['STOIC_CONTROL', 'CBT_REALITY_CHECK', 'ACT_DEFUSION'],
          suggestedReframe: 'Good administrators know that authentic group learning looks active and loud. My clear rubric and student engagement will speak for themselves.',
          reframeOptions: [
            {
              id: 'ref_t4_opt',
              text: 'Constructivist active learning naturally looks and sounds dynamic. I will welcome the administrator calmly, explain the activity objective, and stay anchored in my lesson plan.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Applies Stoic composure and professional pedagogical confidence.',
              clinicalFeedback: 'Demonstrates executive composure under evaluation pressure.',
            },
            {
              id: 'ref_t4_toxic',
              text: 'Observations don’t matter at all! Evaluations are meaningless and I don’t care what anyone thinks!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Defensive indifference that rejects professional feedback.',
              clinicalFeedback: 'Masks anxiety with false apathy.',
            },
            {
              id: 'ref_t4_rat',
              text: 'Administration is out to get me. I should freeze the lesson and make students sit in silent rows immediately.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Reactive panic that disrupts student learning.',
              clinicalFeedback: 'Lets performance anxiety derail sound teaching practice.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_teach_5',
          thought: 'A student muttered a sarcastic insult under their breath when I asked them to open their textbook. They have zero respect for me and the room is laughing.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'PERSONALIZATION',
          explanation: 'Taking a student’s adolescent posturing or emotional defense as a personal attack on your dignity.',
          techniqueOptions: ['SCHEMA_HEALTHY_ADULT', 'STOIC_CONTROL', 'REBT_DISPUTE'],
          suggestedReframe: 'Adolescent defiance is often a defense mechanism against academic insecurity. I will address it privately with calm neutrality, not a public power struggle.',
          reframeOptions: [
            {
              id: 'ref_t5_opt',
              text: 'A student’s sarcastic remark is an expression of their own stress or peer insecurity, not my worth. I will not engage in a public power struggle; I will speak with them privately with calm boundaries.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Maintains adult dignity, avoids power struggles, and protects classroom culture.',
              clinicalFeedback: 'Gold-standard educator response. De-escalates conflict seamlessly.',
            },
            {
              id: 'ref_t5_toxic',
              text: 'They are just joking! Sarcasm is how teenagers show deep love and appreciation!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Ignores necessary boundary enforcement.',
              clinicalFeedback: 'Fails to model healthy boundaries for the classroom.',
            },
            {
              id: 'ref_t5_rat',
              text: 'I must humiliate this student in front of the whole class right now to re-establish total dominance.',
              type: 'RATIONALIZATION',
              score: 10,
              explanation: 'Ego tyranny that damages the teacher-student relationship.',
              clinicalFeedback: 'Creates deep resentment and escalates future defiance.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_teach_6',
          thought: 'In the faculty meeting, colleagues presented intricate digital portfolios while I am barely surviving weekly grading. I am a complete imposter.',
          contextDomain: 'TEACHING_EDUCATOR',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Comparing your daily survival reality with colleagues’ curated professional showcases.',
          techniqueOptions: ['CBT_REALITY_CHECK', 'CFT_COMPASSION', 'BA_MICRO_ACTION'],
          suggestedReframe: 'Every educator has different strengths and stages. My relationship with my students and steady consistency have profound value.',
          reframeOptions: [
            {
              id: 'ref_t6_opt',
              text: 'Every educator has different strengths; aesthetic slide decks do not equal student connection. My warmth, steady consistency, and dedication in the room are what truly impact students.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Disarms imposter syndrome by valuing authentic relational teaching.',
              clinicalFeedback: 'Reclaims personal pedagogical integrity.',
            },
            {
              id: 'ref_t6_toxic',
              text: 'I will copy their exact slides and work 90 hours this week to outshine everyone!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Competitive overcompensation leading straight to medical burnout.',
              clinicalFeedback: 'Drives exhaustion without improving actual student outcomes.',
            },
            {
              id: 'ref_t6_rat',
              text: 'All other teachers are fake politicians. I will isolate myself in my classroom and stop speaking to faculty.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Bitter cynicism that isolates you from supportive community.',
              clinicalFeedback: 'Isolates you from peer support.',
            },
          ],
          isSolved: false,
        },

        // --- PARTNERSHIP & MARRIAGE (Continued) ---
        {
          id: 'thg_rel_4',
          thought: 'We disagreed in front of the kids about bedtime rules. We are terrible parents who are confusing our children with mixed signals.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Viewing a minor parenting calibration disagreement as irreversible damage to child psychology.',
          techniqueOptions: ['CFT_COMPASSION', 'CBT_REALITY_CHECK', 'SCHEMA_HEALTHY_ADULT'],
          suggestedReframe: 'Occasional differing perspectives are normal. When we debrief calmly and show unity afterward, we model healthy communication for our children.',
          reframeOptions: [
            {
              id: 'ref_r4_opt',
              text: 'Parents will occasionally differ in the moment. What matters is supporting each other in real-time, debriefing privately later, and showing our kids that loving adults can calibrate respectfully.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Reframes minor parenting friction into an opportunity for modeled adult teamwork.',
              clinicalFeedback: 'Promotes marital teamwork and healthy child modeling.',
            },
            {
              id: 'ref_r4_toxic',
              text: 'We never disagree! Our parenting philosophies are 100% identical in every universe!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Denies normal human differences.',
              clinicalFeedback: 'Suppresses constructive co-parenting dialogue.',
            },
            {
              id: 'ref_r4_rat',
              text: 'My partner deliberately undermines my authority in front of the kids to make me look like the bad guy.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Paranoid mind-reading that creates marital hostility.',
              clinicalFeedback: 'Fuels adversarial resentment in marriage.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rel_5',
          thought: 'I tried to initiate intimacy tonight and my partner said they are too tired. They no longer find me attractive and our romantic life is dead.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'MIND_READING',
          explanation: 'Conflating physiological bodily exhaustion from childcare/work with personal sexual rejection.',
          techniqueOptions: ['CBT_REALITY_CHECK', 'CFT_COMPASSION', 'STOIC_CONTROL'],
          suggestedReframe: 'Exhaustion after parenting and working is physical, not an absence of desire. I can offer a back massage and cuddle without pressure.',
          reframeOptions: [
            {
              id: 'ref_r5_opt',
              text: 'Physical exhaustion from parenting and work is a biological reality, not a loss of attraction. I will offer a warm hug, cuddle without pressure, and schedule focused time when energy allows.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Decouples tiredness from self-worth and preserves relational warmth.',
              clinicalFeedback: 'Prevents the deadly shame-pressure-withdrawal cycle in intimacy.',
            },
            {
              id: 'ref_r5_toxic',
              text: 'Romance is overrated; as long as the mortgage is paid, marriages don’t need closeness!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Rationalizes emotional drift to avoid vulnerability.',
              clinicalFeedback: 'Resigns to roommate marriage syndrome.',
            },
            {
              id: 'ref_r5_rat',
              text: 'I will pull away emotionally and withhold affection until they prove they still care about me.',
              type: 'RATIONALIZATION',
              score: 10,
              explanation: 'Punitive withdrawal that damages attachment security.',
              clinicalFeedback: 'Accelerates marital disconnection.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rel_6',
          thought: 'An unexpected major car repair bill arrived. We will never get ahead financially and I am failing to provide security for our family.',
          contextDomain: 'PARTNERSHIP_INTIMACY',
          correctDistortion: 'CATASTROPHIZING',
          explanation: 'Treating a standard unforeseen life maintenance cost as permanent financial catastrophe.',
          techniqueOptions: ['STOIC_CONTROL', 'CBT_REALITY_CHECK', 'BA_MICRO_ACTION'],
          suggestedReframe: 'Unexpected expenses are an inevitable part of owning assets. We have weathered challenges before; we will review our budget calmly as a team.',
          reframeOptions: [
            {
              id: 'ref_r6_opt',
              text: 'Unexpected expenses are routine bumps in life, not evidence of financial doom or failure. We will review our budget calmly as a team and adjust this month’s discretionary spending.',
              type: 'OPTIMAL',
              score: 96,
              explanation: 'Applies Stoic reality testing and active problem-solving.',
              clinicalFeedback: 'Transforms catastrophic panic into calm marital financial stewardship.',
            },
            {
              id: 'ref_r6_toxic',
              text: 'Money is an illusion! The universe will miraculously drop cash into our bank account tomorrow!',
              type: 'TOXIC_POSITIVITY',
              score: 25,
              explanation: 'Magical thinking that evades financial responsibility.',
              clinicalFeedback: 'Avoids practical budget calibration.',
            },
            {
              id: 'ref_r6_rat',
              text: 'It’s my partner’s fault for driving the car so much. I will complain about this for the next month.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Blaming partner to discharge personal anxiety.',
              clinicalFeedback: 'Creates marital resentment over unavoidable maintenance.',
            },
          ],
          isSolved: false,
        },

        // --- SELF-RESTORATION & REST (Continued) ---
        {
          id: 'thg_rest_4',
          thought: 'I feel deeply sad and overwhelmed today, but I cannot show any weakness or emotion because a father and teacher must be an unshakable rock.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'SHOULD_STATEMENTS',
          explanation: 'Believing that suppression of human emotion equals strength, leading to sudden emotional explosion or numbness.',
          techniqueOptions: ['SCHEMA_HEALTHY_ADULT', 'CFT_COMPASSION', 'ACT_DEFUSION'],
          suggestedReframe: 'True strength is acknowledging vulnerability and processing it with dignity. Modeling emotional honesty teaches my children and students how to handle hardship.',
          reframeOptions: [
            {
              id: 'ref_s4_opt',
              text: 'Suppressing emotions does not make me strong; it makes me brittle. Acknowledging my strain, taking a quiet moment of self-care, and modeling authentic resilience is the highest form of leadership.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Replaces toxic emotional repression with mature Healthy Adult sovereignty.',
              clinicalFeedback: 'Profoundly restorative. Protects long-term psychological health.',
            },
            {
              id: 'ref_s4_toxic',
              text: 'Men don’t feel sadness! Just bottle everything up and swallow it forever!',
              type: 'TOXIC_POSITIVITY',
              score: 15,
              explanation: 'Toxic emotional suppression that drives psychosomatic illness.',
              clinicalFeedback: 'Directly causes cardiovascular strain and emotional explosion.',
            },
            {
              id: 'ref_s4_rat',
              text: 'Since no one cares how hard my life is, I might as well numb out with alcohol and video games.',
              type: 'RATIONALIZATION',
              score: 15,
              explanation: 'Self-pitying avoidance that avoids constructive support.',
              clinicalFeedback: 'Escapes into destructive numbing behaviors.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rest_5',
          thought: 'It is Sunday 6 PM and my chest is tight with dread about tomorrow’s school schedule. My entire weekend was wasted and I am already exhausted.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'EMOTIONAL_REASONING',
          explanation: 'Treating Sunday evening anticipatory anxiety as proof that the entire weekend was futile and tomorrow will be terrible.',
          techniqueOptions: ['ACT_DEFUSION', 'SOMATIC_COREGULATION', 'BA_MICRO_ACTION'],
          suggestedReframe: 'Anticipatory anxiety is just my nervous system shifting gears. Tonight is still my evening; I will take a warm shower and enjoy dinner in the present moment.',
          reframeOptions: [
            {
              id: 'ref_s5_opt',
              text: 'Sunday evening dread is just anticipatory mental noise, not reality. Tonight is still my time. I will do 2 physiological sighs, enjoy dinner with my family, and focus only on the present hour.',
              type: 'OPTIMAL',
              score: 97,
              explanation: 'Defuses anticipatory anxiety and reclaims Sunday evening presence.',
              clinicalFeedback: 'Stops tomorrow’s worries from stealing tonight’s peace.',
            },
            {
              id: 'ref_s5_toxic',
              text: 'Mondays are the greatest days in human history! I am overjoyed to work 12 hours tomorrow!',
              type: 'TOXIC_POSITIVITY',
              score: 30,
              explanation: 'Forced cheer that feels dishonest to the nervous system.',
              clinicalFeedback: 'Invalidates genuine work fatigue.',
            },
            {
              id: 'ref_s5_rat',
              text: 'My career is a prison. I will lie on the floor and doomscroll until 2 AM to avoid tomorrow.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Revenge bedtime procrastination that sabotages Monday.',
              clinicalFeedback: 'Guarantees the exact exhaustion you fear.',
            },
          ],
          isSolved: false,
        },
        {
          id: 'thg_rest_6',
          thought: 'It is 11:30 PM and I am still scrolling on my phone in bed. I know I will regret this tomorrow, but this is the only time nobody is asking me for something.',
          contextDomain: 'SELF_RESTORATION',
          correctDistortion: 'ALL_OR_NOTHING',
          explanation: 'Sacrificing restorative sleep to claim a counterfeit sense of nocturnal freedom.',
          techniqueOptions: ['BA_MICRO_ACTION', 'CFT_COMPASSION', 'SCHEMA_HEALTHY_ADULT'],
          suggestedReframe: 'My desire for autonomy is valid, but digital scrolling steals the deep rest I need to feel good tomorrow. I will put the phone on the dresser and read 5 minutes in dim light.',
          reframeOptions: [
            {
              id: 'ref_s6_opt',
              text: 'My need for quiet personal time is completely valid, but screen scrolling steals tomorrow’s vitality. I will honor my need for rest by plugging my phone across the room and reading a physical book for 5 minutes.',
              type: 'OPTIMAL',
              score: 98,
              explanation: 'Validates the legitimate need for autonomy while choosing true restorative sleep.',
              clinicalFeedback: 'Directly breaks the revenge bedtime procrastination loop.',
            },
            {
              id: 'ref_s6_toxic',
              text: 'Phone scrolling is pure self-care and I should do it all night long without guilt!',
              type: 'TOXIC_POSITIVITY',
              score: 35,
              explanation: 'Mistaking dopaminergic stimulation for restorative care.',
              clinicalFeedback: 'Reinforces sleep deprivation.',
            },
            {
              id: 'ref_s6_rat',
              text: 'My life has so little freedom that scrolling until 1 AM is my only rebellion against duty.',
              type: 'RATIONALIZATION',
              score: 20,
              explanation: 'Victim mentality that harms your own body.',
              clinicalFeedback: 'Punishes your own nervous system to feel a momentary illusion of rebellion.',
            },
          ],
          isSolved: false,
        },
      ];
